version: '3.5'

# For this configuration to work properly, you must have a license file mounted into the dotcms service.
# Without a license file, the external ES service will NOT be recognized and utilized.  All documents will
# indexed on the dotcms node directly and will not be persisted between restarts.

networks:
  http_net:
  db_net:
  es_net:
  hz_net:

volumes:
  cms-shared:
  #cms-local:
  dbdata:
  esdata:

services:
  http:
    image: dotcms/haproxy:latest
    environment:
      "HAPROXY_CERT_PATH": '/certs/'
#      "HAPROXY_REDIRECT_HTTPS_ALL": 'true'
#      "HAPROXY_MAINTENANCE_PAGE": '/srv/config/503.http'

    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - /data/dotcms/haproxy/certs:/certs:ro
#      - /data/dotcms/haproxy/503.http:/srv/config/503.http:ro

    networks:
      - http_net

  hazelcast:
    image: dotcms/hazelcast:latest
    environment:
      "PROVIDER_HAZELCAST_DNSNAMES": 'hazelcast'
      "PROVIDER_HAZELCAST_HEAP_MIN": '128m'
      "PROVIDER_HAZELCAST_HEAP_MAX": '512m'
      "PROVIDER_HAZELCAST_MANCENTER_ENABLED": 'true'
      "PROVIDER_HAZELCAST_MANCENTER_URL": 'http://hazelcast-mancenter:8080/mancenter'
    networks:
      - hz_net

  #hazelcast-mancenter is a totally optional service that provides insights into 
  # the hazelcast cache.  It will function for a cluster of up to two hazelcast
  # nodes.  If you wish to use it with clusters with more than two nodes, you 
  # will need to purchase a license from Hazelcast.
  # https://docs.hazelcast.org/docs/latest-development/manual/html/License_Questions.html
  hazelcast-mancenter:
    image: dotcms/hazelcast-mancenter:latest
    ports:
      - "8080:8080"
    networks:
      - hz_net

  elasticsearch:
    image: dotcms/es-open-distro:latest
    environment:
      "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1024m'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch'
      "ES_ADMIN_PASSWORD": 'admin'
    networks:
      - es_net

  dotcms:
    image: dotcms/dotcms:latest
    environment:
      "CMS_HEAP_SIZE": '2g'
      "CMS_JAVA_OPTS": '-XX:+PrintFlagsFinal'
      "PROVIDER_DB_DNSNAME": 'db'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch'
      "PROVIDER_HAZELCAST_DNSNAMES": 'hazelcast'
      "ES_ADMIN_PASSWORD": 'admin'
    depends_on:
      - elasticsearch
      - hazelcast
      - db
      - http
    volumes:
      - cms-shared:/data/shared
      #- [serverpath]/license.dat:/data/local/dotsecure/license/license.dat
      #- [serverpath]/license.zip:/data/shared/assets/license.zip
    networks:
      - db_net
      - http_net
      - es_net
      - hz_net

  db:
    image: dotcms/postgres:latest
    volumes:
      - dbdata:/data/pg
    networks:
      - db_net
